CREATE TABLE users
(
    user_id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username        VARCHAR(50)                             NOT NULL,
    email           VARCHAR(50)                             NOT NULL,
    hashed_password VARCHAR(64)                             NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (user_id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);