CREATE TABLE cart_items
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cart_id    BIGINT                                  NOT NULL,
    product_id BIGINT                                  NOT NULL,
    quantity   INTEGER                                 NOT NULL,
    price      DECIMAL(19, 2)                          NOT NULL,
    version    BIGINT,
    CONSTRAINT pk_cart_items PRIMARY KEY (id)
);

CREATE TABLE carts
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    session_id VARCHAR(36)                 NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_carts PRIMARY KEY (id)
);

ALTER TABLE carts
    ADD CONSTRAINT uk_cart_session_id UNIQUE (session_id);

CREATE UNIQUE INDEX idx_cartitem_cartid_productid ON cart_items (cart_id, product_id);

ALTER TABLE cart_items
    ADD CONSTRAINT FK_CART_ITEMS_ON_CART FOREIGN KEY (cart_id) REFERENCES carts (id);